name = "bingow"
description = ""
version = "0.1.0-dev"

authors = ["Mateus Honduras"]
maintainers = ["Mateus Honduras <mateus.honduras@outlook.com.br>"]
maintainers-logins = ["mashondu"]
licenses = "MPL-2.0"
website = ""
tags = []
